"""Encoder-matrix tests for retention.codec.normalize_codec.

The point of this suite is to prove encoder-agnosticism: corruption is
generated by simulating *different* encoders (each legacy codec pair, alone
and chained), and the normalizer must recover the exact original in every
case while leaving clean text byte-identical.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # splinter-memory root

from retention.codec import normalize_codec  # noqa: E402


def misdecode(original: str, codec: str, errors: str = "strict") -> str:
    """Simulate an encoder boundary that misreads UTF-8 bytes as ``codec``.

    Real pipelines hitting bytes undefined in the claimed codec (e.g. 0x9D in
    cp1252) usually substitute U+FFFD rather than crash, so case generators
    use errors="replace" to stay realistic; targeted tests keep "strict".
    """
    return original.encode("utf-8").decode(codec, errors=errors)


# ---------------------------------------------------------------------------
# 1. Single-pass corruption, one codec pair at a time
# ---------------------------------------------------------------------------

def test_emdash_cp1252():
    original = "Fix applied — verified this round."
    assert normalize_codec(misdecode(original, "cp1252")) == original


def test_arrow_latin1():
    original = "ingest → store → re-inject"
    assert normalize_codec(misdecode(original, "latin-1")) == original


def test_curly_quotes_cp1252():
    original = 'He said "stop it" repeatedly.'
    assert normalize_codec(misdecode(original, "cp1252")) == original


def test_copyright_latin1():
    # C2 A9 family: Â© is the classic latin-1 misdecode of ©
    original = "© 2026 splinter"
    assert normalize_codec(misdecode(original, "latin-1")) == original


def test_bullet_cp1252():
    original = "- item one\n• item two"
    assert normalize_codec(misdecode(original, "cp1252")) == original


# ---------------------------------------------------------------------------
# 2. Chained corruption (mojibake of mojibake, mixed codec chains)
# ---------------------------------------------------------------------------

def test_double_latin1_then_cp1252():
    original = "turn 35 → 36: decay=1.0 — no eviction"
    once = misdecode(original, "latin-1")
    twice = misdecode(once, "cp1252")
    assert normalize_codec(twice) == original


def test_double_cp1252_then_latin1():
    # Note: avoid U+201D (E2 80 9D) in the first pass — 0x9D is undefined in
    # cp1252, so a real cp1252 pipeline could not have produced that chain.
    original = "‘quoted’ — dashed → arrowed"
    once = misdecode(original, "cp1252")
    twice = misdecode(once, "latin-1")
    assert normalize_codec(twice) == original


# ---------------------------------------------------------------------------
# 2b. Mixed segments: clean non-Latin-1 chars alongside corrupted segments
#     (the dominant real-data pattern — whole-string round-trips cannot
#     encode the clean part, so segmentation is required)
# ---------------------------------------------------------------------------

def test_mixed_clean_arrow_with_corrupted_dash():
    # original had a clean arrow AND an em-dash; only the dash got mangled
    original = "ingest → store — re-inject"
    import codecs as _c
    mangled = original.replace("—", misdecode("—", "latin-1"))
    assert normalize_codec(mangled) == original


def test_mixed_cjk_with_corrupted_segment():
    original = "GPU 状态: RX 7900 XTX — verified → ok"
    mangled = original.replace("—", misdecode("—", "cp1252")).replace("→", misdecode("→", "latin-1"))
    assert normalize_codec(mangled) == original


def test_mixed_user_quoted_partial_fragment_untouched():
    # User retyped a 2-byte fragment of a 3-byte shard ("â\x86" + ASCII quote):
    # not valid mojibake, no original to recover — must stay byte-identical.
    text = 'I still see mentions of "â\x86" in sentences'
    assert normalize_codec(text) == text


# ---------------------------------------------------------------------------
# 3. Clean text must pass through byte-identical (no false positives)
# ---------------------------------------------------------------------------

def test_clean_ascii_unchanged():
    text = "plain ascii with no high bytes at all 0123456789"
    assert normalize_codec(text) == text


def test_clean_proper_unicode_unchanged():
    text = "café naïve château — done → next © “fine” • ok"
    assert normalize_codec(text) == text


def test_legitimate_a_circumflex_unchanged():
    # â is a real French letter; repair must NOT fire on clean French.
    for word in ("mâchoire", "châtelain", "rêve", "cœur"):
        assert normalize_codec(word) == word


def test_empty_and_none_safe():
    assert normalize_codec("") == ""


# ---------------------------------------------------------------------------
# 4. Invariants: idempotence + never-destroy on every case above
# ---------------------------------------------------------------------------

def _all_cases() -> list[str]:
    originals = [
        "Fix applied — verified this round.",
        "ingest → store → re-inject",
        'He said "stop it" repeatedly.',
        "© 2026 splinter",
        "- item one\n• item two",
        "café naïve château — done → next © “fine” • ok",
        "mâchoire rêve cœur",
    ]
    cases = []
    for o in originals:
        cases.append(o)                                  # clean
        cases.append(misdecode(o, "cp1252", errors="replace"))   # one encoder
        cases.append(misdecode(o, "latin-1"))                    # another encoder
        cases.append(misdecode(misdecode(o, "latin-1"), "cp1252", errors="replace"))  # chained
    return cases


def test_idempotent_on_all_cases():
    for text in _all_cases():
        once = normalize_codec(text)
        twice = normalize_codec(once)
        assert once == twice, f"not idempotent for {text!r}"


def test_never_increases_corruption():
    from retention.codec import _corruption_score
    for text in _all_cases():
        out = normalize_codec(text)
        assert _corruption_score(out) <= _corruption_score(text), (
            f"repair made it worse: {text!r} -> {out!r}"
        )


if __name__ == "__main__":
    failed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"PASS {name}")
            except AssertionError as exc:
                failed += 1
                print(f"FAIL {name}: {exc}")
    sys.exit(1 if failed else 0)
